name: Comprobacion de Tokens

on: [push]

jobs:
  verificar-tokens:
    runs-on: self-hosted
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Comparar DEV_TOKEN contra LOCAL_DEV_TOKEN
        env:
          DEV_TOKEN_SECRET: ${{ secrets.DEV_TOKEN }}
        shell: powershell
        run: |
          Write-Host "Verificando coincidencia de tokens..."
          $envSecret = $env:DEV_TOKEN_SECRET
          $envLocal = $env:LOCAL_DEV_TOKEN

          if ($envSecret -eq $envLocal) {
              Write-Host "SUCCESS: El DEV_TOKEN (Secret) coincide exactamente con LOCAL_DEV_TOKEN (Variable local)."
              exit 0
          } else {
              Write-Error "ERROR: El DEV_TOKEN no coincide con la variable LOCAL_DEV_TOKEN."
              exit 1
          }
